/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultPersonIdRouteImport } from './routes/vault.$personId'
import { Route as GameTaskIdRouteImport } from './routes/game.$taskId'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultPersonIdRoute = VaultPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => VaultRoute,
} as any)
const GameTaskIdRoute = GameTaskIdRouteImport.update({
  id: '/game/$taskId',
  path: '/game/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calls': typeof CallsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/lessons': typeof LessonsRoute
  '/office': typeof OfficeRoute
  '/vault': typeof VaultRouteWithChildren
  '/game/$taskId': typeof GameTaskIdRoute
  '/vault/$personId': typeof VaultPersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calls': typeof CallsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/lessons': typeof LessonsRoute
  '/office': typeof OfficeRoute
  '/vault': typeof VaultRouteWithChildren
  '/game/$taskId': typeof GameTaskIdRoute
  '/vault/$personId': typeof VaultPersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calls': typeof CallsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/lessons': typeof LessonsRoute
  '/office': typeof OfficeRoute
  '/vault': typeof VaultRouteWithChildren
  '/game/$taskId': typeof GameTaskIdRoute
  '/vault/$personId': typeof VaultPersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/calls'
    | '/compliance'
    | '/copilot'
    | '/lessons'
    | '/office'
    | '/vault'
    | '/game/$taskId'
    | '/vault/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/calls'
    | '/compliance'
    | '/copilot'
    | '/lessons'
    | '/office'
    | '/vault'
    | '/game/$taskId'
    | '/vault/$personId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/calls'
    | '/compliance'
    | '/copilot'
    | '/lessons'
    | '/office'
    | '/vault'
    | '/game/$taskId'
    | '/vault/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CallsRoute: typeof CallsRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  LessonsRoute: typeof LessonsRoute
  OfficeRoute: typeof OfficeRoute
  VaultRoute: typeof VaultRouteWithChildren
  GameTaskIdRoute: typeof GameTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$personId': {
      id: '/vault/$personId'
      path: '/$personId'
      fullPath: '/vault/$personId'
      preLoaderRoute: typeof VaultPersonIdRouteImport
      parentRoute: typeof VaultRoute
    }
    '/game/$taskId': {
      id: '/game/$taskId'
      path: '/game/$taskId'
      fullPath: '/game/$taskId'
      preLoaderRoute: typeof GameTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VaultRouteChildren {
  VaultPersonIdRoute: typeof VaultPersonIdRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultPersonIdRoute: VaultPersonIdRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CallsRoute: CallsRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  LessonsRoute: LessonsRoute,
  OfficeRoute: OfficeRoute,
  VaultRoute: VaultRouteWithChildren,
  GameTaskIdRoute: GameTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
